---
title: "models"
author: "Dan, Sarah, and Brian"
date: "4/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)
library(tidyverse)
library(xgboost)
library(caret)
library(kernlab)
library(randomForest)
```

- load data sets

```{r}
student.data.complete <- read.csv(file='./data/student_data_complete.csv')
student.evaluation.complete <- read.csv(file='./data/student_evaluation_complete.csv')
```

- train/test split

```{r}
set.seed(123)

part <- createDataPartition(student.data.complete$ph, p=0.8, list=FALSE)
training <- student.data.complete %>%
  filter(row_number() %in% part)
validation <- student.data.complete %>%
  filter(!row_number() %in% part)
```

- prepare data from training by turning into lists

```{r}
listify <- function(data){
  return(list('y' = data$ph, 'x' = data %>% select(-ph)))
}

student.data.complete <- listify(student.data.complete)
student.evaluation.complete <- listify(student.evaluation.complete)
training <- listify(training)
validation <- listify(validation)
```

<h1> XG Boost</h1>

- hyper parameters (selected via exploration)

```{r}
grid <- expand.grid(nrounds = 2500,
                    max_depth = 6,
                    eta = 0.03,
                    gamma = 0,
                    colsample_bytree = 1,
                    min_child_weight = 1,
                    subsample = 0.5)

control <- trainControl(method='cv',
                        number=10,
                        allowParallel = TRUE)
```

- train model

```{r}
model <- train(x = training$x,
             y = training$y,
             method = 'xgbTree',
             tuneGrid = grid,
             metric = 'RMSE',
             trControl = control)

model$results
```

- most important predictors

```{r}
model %>%
  varImp() %>%
  plot()
```

<h1> Support Vector Machine</h1>

```{r, message=FALSE, warning=FALSE,cache=TRUE}
set.seed(200)
svmRTuned <- train(x = training$x,
                   y = training$y,
                   method="svmRadial", 
                   preProc=c("center","scale"),
                   tuneLength = 14,
                   trControl = trainControl(method="cv"))

svmRTuned
svmRTuned$finalModel
```

```{r}
svmRTuned %>%
  varImp() %>%
  plot()
```

<h2>Random Forest</h2>

```{r warning=FALSE, message=FALSE, cache=TRUE}
set.seed(200)
rf <- randomForest(x = training$x,
                   y = training$y, 
                   importance=TRUE,
                   ntree=1000)

best_tree <- which(rf$mse==min(rf$mse))
sqrt(rf$mse[best_tree])
rf$rsq[best_tree]
```

```{r}
rf$importance 
```

<h2> Final Results </h2>

- validation rmse (only run on final, best model)

```{r}
postResample(predict(svmRTuned, newdata=validation$x), validation$y)
```

- retraining on ALL data

```{r}
final.model <- train(x = student.data.complete$x,
                     y = student.data.complete$y,
                     method = 'xgbTree',
                     tuneGrid = grid,
                     metric = 'RMSE')
```

- final predictions

```{r}
predictions <- predict(final.model, newdata=student.evaluation.complete$x)
```

```{r}
predictions
```

